import { connect } from 'dva';
import DocumentTitle from 'react-document-title';
import { formatMessage } from 'umi/locale';
// import IndexView from './Index.jsx';

import styles from './style.less';

const Index = ({ blockItem }) => {

  if (!blockItem || blockItem.success === false) {
    return null;
  }

  const { block } = blockItem;

  console.log(block)

  return (
    <DocumentTitle title={`AvatarX - ${formatMessage({ id: 'app.common.slogan' })}`}>
      <div className="templates-wrapper">
        <div className="content-template">
          <h1>Block</h1>
          <div className={`content ${styles['content-block']}`}>
            <div className={styles.header}>
              <p>Block Id</p>
              <h3>{block.id}</h3>
            </div>
            <ul className={`clearfix ${styles.detail}`}>
              <li>
                <span>Transactions</span>
                <span>{block.numberOfTransactions}</span>
              </li>
              <li>
                <span>Confirmations</span>
                <span>{block.confirmations}</span>
              </li>
              <li>
                <span>Height</span>
                <span>{block.height}</span>
              </li>
              <li>
                <span>Reward</span>
                <span>{block.reward}</span>
              </li>
              <li>
                <span>Total Fee</span>
                <span>{block.totalFee}</span>
              </li>
              <li>
                <span>Total Forged</span>
                <span>{block.totalForged}</span>
              </li>
              <li>
                <span>Total Amount</span>
                <span>{block.totalAmount}</span>
              </li>
              <li>
                <span>Generated by</span>
                <span>{block.generatorId}</span>
              </li>
              <li>
                <span>Timestamp</span>
                <span>{block.timestamp}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </DocumentTitle>
  );
}

const mapStateToProps = (state) => {
  const { blockItem } = state.blocks;

  return {
    blockItem,
  };
}

export default connect(mapStateToProps)(Index);
