
export default {
  'app.common.slogan': 'AvatarX Explorer',

  'app.header.menu.home': 'Home',
  'app.header.menu.accounts': 'Wallets',
  'app.header.menu.delegates': 'Delegates',

  'app.header.lang': '中文',


  'app.index.latest-blocks': 'Lastest Blocks',
  'app.index.latest-transactions': 'Lastest Transactions',

  'app.index.blocks.column-id': 'Block ID',
  'app.index.blocks.column-height': 'Height',
  'app.index.blocks.column-timestamp': 'Timestamp',
  'app.index.blocks.column-transactions': 'Transactions',
  'app.index.blocks.column-generator': 'Generated by',
  'app.index.blocks.column-total-amount': 'Amount(ATC)',
  'app.index.blocks.column-reward': 'Fee(ATC)',

  'app.index.transactions.column-id': 'ID',
  'app.index.transactions.column-timestamp': 'Timestamp',
  'app.index.transactions.column-sender': 'Sender',
  'app.index.transactions.column-recipient': 'Recipient',
  'app.index.transactions.column-total-amount': 'Amount(ATC)',
  'app.index.transactions.column-total-fee': 'Fee(ATC)',


  'app.blocks.detail.title': 'Block',
  'app.blocks.detail.row-transactions': 'Transactions',
  'app.blocks.detail.row-confirmations': 'Confirmations',
  'app.blocks.detail.row-height': 'Height',
  'app.blocks.detail.row-reward': 'Reward',
  'app.blocks.detail.row-total-fee': 'Total Fee',
  'app.blocks.detail.row-total-forged': 'Total Forged',
  'app.blocks.detail.row-total-amount': 'Total Amount',
  'app.blocks.detail.row-generator': 'Generated by',
  'app.blocks.detail.row-timestamp': 'Timestamp',


  'app.accounts.top': 'Top Wallets',
  'app.accounts.top.column-rank': 'Rank',
  'app.accounts.top.column-address': 'Address',
  'app.accounts.top.column-balance': 'Balance',
  'app.accounts.top.column-percent': 'Supply',

  'app.accounts.detail.title': 'Wallet Summary',
  'app.accounts.detail.address': 'Address',
  'app.accounts.detail.row-balance': 'Balance',
  'app.accounts.detail.row-lock-height': 'Lock Hieght',


  'app.delegates.title': 'Delegates',
  'app.delegates.list.column-rank': 'Rank',
  'app.delegates.list.column-name': 'Name',
  'app.delegates.list.column-forged-blocks': 'Forged Blocks',
  'app.delegates.list.column-missed-blocks': 'Missed Blocks',
  'app.delegates.list.column-rewards': 'Reward',
  'app.delegates.list.column-vote': 'Votes',
  'app.delegates.list.column-productivity': 'Productivity',
  'app.delegates.list.column-approval': 'Approval',


  'app.footer.slogan': 'Personalized Artificial Intelligence Network',
  'app.footer.product-title': 'Product',
  'app.footer.product-child-github': 'GitHub repository',
  'app.footer.product-child-block-browser': 'Block browser',
  'app.footer.product-child-web-wallet': 'Online Wallet',
  'app.footer.product-child-dapps': 'Dapps',
  'app.footer.product-child-whitepaper': 'Whitepaper',

  'app.footer.contact-title': 'Contact',
  'app.footer.contact-child-bd': 'BD: bd@avatarx.io',
  'app.footer.contact-child-support': 'Support: support@avatarx.io',
  'app.footer.contact-child-wechat': 'Wechat: 181 6524 5633',

  'app.footer.wxmp-title': 'Wechat',
  'app.footer.weibo-title': 'Weibo',
};
